
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:open_filex/open_filex.dart';
import 'package:provider/provider.dart';
import 'package:selc_admin/components/alert_dialog.dart';
import 'package:selc_admin/components/button.dart';
import 'package:selc_admin/components/donwloader_util/file_downloader.dart';
import 'package:selc_admin/components/text.dart';
import 'package:selc_admin/model/models.dart';
import 'package:selc_admin/providers/pref_provider.dart';
import 'package:selc_admin/providers/selc_provider.dart';


class ReportWizard extends StatefulWidget {

  final String? reportType;
  final int? id;
  final String? fileType;
  final int? semester;
  final int? year;

  const ReportWizard({super.key, this.reportType, this.id, this.fileType, this.semester, this.year});

  @override
  State<ReportWizard> createState() => _ReportWizardState();

}

class _ReportWizardState extends State<ReportWizard> {

  final reportTypeController = DropdownController<String>();

  final fileTypeController = DropdownController<String>();
  
  final departmentController = DropdownController<Department>();

  final classCourseController = DropdownController<ClassCourse>();

  final semesterController = DropdownController<int>();

  final yearController = DropdownController<int>();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    if(widget.reportType == null) return; 

    reportTypeController.value = widget.reportType;


    if(widget.reportType == 'Department'){
      departmentController.value = Provider.of<SelcProvider>(context, listen: false)
          .departments.firstWhere(
            (element) => element.departmentId == widget.id);
    }

    if(widget.reportType == 'Class Course'){
      classCourseController.value = Provider.of<SelcProvider>(context, listen: false)
          .classCourses.firstWhere(
            (element) => element.classCourseId == widget.id);
    }


    semesterController.value = widget.semester ?? Provider.of<SelcProvider>(context, listen: false).generalSetting.currentSemester;
    yearController.value = widget.year ?? Provider.of<SelcProvider>(context, listen: false).generalSetting.academicYear;


    fileTypeController.value = widget.fileType ?? '.xlsx'; //excel report is generated by default.


    
  }

  @override
  Widget build(BuildContext context) {

    return Container(
      padding: const EdgeInsets.all(16),
      width: MediaQuery.of(context).size.width * 0.25,
      margin: const EdgeInsets.fromLTRB(0, 12, 0, 12),

      decoration: BoxDecoration(
        color: PreferencesProvider.getColor(context, 'primary-color'),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.green.shade400, width: 1.5)
      ),

      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [

          Row(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              HeaderText('Report Wizard'),

              Spacer(),

              IconButton(
                onPressed: () => Navigator.pop(context),
                icon: Icon(CupertinoIcons.xmark, color: Colors.red.shade400,),
              )
            ],
          ),

          const SizedBox(height: 16,),


          //todo: report_type

          CustomText('Report Type: '),

          const SizedBox(height: 8,),

          CustomDropdownButton<String>(
            controller: reportTypeController,
            hint: 'Select Report Type',
            items: ['Admin', 'Department', 'Class Course'],
            onChanged: (newValue) => setState(() {
              //NOTE: pdf report generation is only exclusive to Class Courses
              if(newValue! != 'Class Course'){
                fileTypeController.value = '.xlsx';
              }
            })
          ),


          const SizedBox(height: 12,),


          //todo: file_extension
          CustomText('File Type: '),

          const SizedBox(height: 8,),


          IgnorePointer(
            ignoring: reportTypeController.value != 'Class Course',
            child: CustomDropdownButton<String>(
              controller: fileTypeController,
              hint: 'Select File Type',
              items: ['.xlsx', '.pdf'],
              onChanged: (newValue) => setState(() {})
            ),
          ),


          if(reportTypeController.value != null) const SizedBox(height: 12,),


          if(reportTypeController.value == 'Department') buildDepartmentDropdown(),

          if(reportTypeController.value == 'Class Course') buildClassCourseDropDown(),


          if(["Department", "Admin"].contains(reportTypeController.value))const SizedBox(height: 12,),

          if(["Department", "Admin"].contains(reportTypeController.value)) buildYearSemesterDropdown(),


          const SizedBox(height: 16,),


          CustomButton.withText(
            'Generate / Download',
            width: double.infinity,
            onPressed: handleGenerateReport
          )

        ]
      ),
    );
  }
  
  
  Widget buildDepartmentDropdown() => Column(  
    mainAxisAlignment: MainAxisAlignment.start,
    crossAxisAlignment: CrossAxisAlignment.start,
    mainAxisSize: MainAxisSize.min,
    spacing: 8,
    children: [
      
      CustomText('Department: '),
      
      
      CustomDropdownButton<Department>(
        controller: departmentController,
        hint: 'Select Department',
        items: Provider.of<SelcProvider>(context).departments, 
        onChanged: (newValue) => setState(() {})
      )
      
    ],
  );




  Widget buildClassCourseDropDown() => Column(
    mainAxisAlignment: MainAxisAlignment.start,
    crossAxisAlignment: CrossAxisAlignment.start,
    mainAxisSize: MainAxisSize.min,
    spacing: 8,
    children: [

      CustomText('Class Course: '),


      CustomDropdownButton<ClassCourse>(
        controller: classCourseController,
        hint: 'Select ClassCourse',
        items: Provider.of<SelcProvider>(context).classCourses,
        onChanged: (newValue) => setState(() {})
      )

    ],
  );



  Widget buildYearSemesterDropdown() => Column(
    mainAxisAlignment: MainAxisAlignment.start,
    crossAxisAlignment: CrossAxisAlignment.start,
    mainAxisSize: MainAxisSize.min,
    spacing: 8,
    children: [

      //todo: Academic Year
      CustomText('Academic Year: '),

      CustomDropdownButton<int>(
        controller: yearController,
        hint: 'Select Academic Year',
        items: List<int>.generate(DateTime.now().year - 2011, (index) => DateTime.now().year - index),
        onChanged: (newValue){}
      ),


      const SizedBox(),


      CustomText('Semester: '),

      CustomDropdownButton<int>(
          controller: semesterController,
          hint: 'Select Semester',
          items: [1, 2],
          onChanged: (newValue){}
      ),

    ],
  );




  Map<String, dynamic> generateReportParams () {

    String reportType = formatReportTypeStr(reportTypeController.value ?? 'admin');

    final Map<String, dynamic> reportParams = {
      'report_type': reportType,
    };

    if(['admin', 'department'].contains(reportType)){
      reportParams.addAll({
        'semester': semesterController.value,
        'year': yearController.value,
      });
    }


    if(reportType == 'department'){
      reportParams.addAll({'id': departmentController.value!.departmentId});
    }else if(reportType == 'class_course'){
      reportParams.addAll({'id': classCourseController.value!.classCourseId});
    }


    reportParams['file_type'] = fileTypeController.value ?? '.xlsx';


    return reportParams;

  }




  void handleGenerateReport() async {

    Map<String, dynamic> reportParams = generateReportParams();


    ReportFile? reportFile;

    try {

      reportFile = await Provider.of<PreferencesProvider>(
          context, listen: false).generateReportFile(reportParams);


    } on SocketException{
      showNoConnectionAlertDialog(context);
      return;
    }on Error{
      showCustomAlertDialog(context, title: 'Error', contentText: 'Could not generate report. An unknown error occurred.');
      return;
    }


    if(reportFile == null){
      showCustomAlertDialog(context, title: 'Error', contentText: 'Could not generate report. An unknown error occurred.');
      return;
    }


    //download the file immediately after generation
    FileDownloader downloader = getDownloader();

    try{


      if(!kIsWeb){
        showDialog( 
          context: context, 
          builder: (_) => LoadingDialog(
            message: 'Downloading report file please wait',
          )
        );
      }

      await downloader.download(context: context, reportFile: reportFile);

      if(!kIsWeb) {
        Navigator.pop(context); //close the loading dialog


        //show a success dialog
        showCustomAlertDialog( 
          context, 
          alertType: AlertType.success,
          title: 'File Download',
          contentText: 'Report file has been downloaded.',
          controls: [
            
            TextButton(
              child: CustomText(  
                'Show File',
                fontWeight: FontWeight.w600,
                textColor: Colors.green.shade400,
              ), 

              onPressed: () async {

                Navigator.pop(context); //closes the current alert dialog

                await OpenFilex.open(
                  reportFile!.localFilePath!,
                  type: reportFile.fileType
                );
              }
            ), 

          ]
        );
      }

    }on Exception catch(e, trace){
    
      debugPrintStack(
        label: e.toString(),
        stackTrace: trace
      );

      showCustomAlertDialog(
        context,
        alertType: AlertType.warning,
        title: 'Download Error',
        contentText: e.toString()
      );

    }

  }


  String formatReportTypeStr(String typeStr){
    //replace whitespace with underscore
    typeStr = typeStr.toLowerCase().replaceAll(' ', '_');
    return typeStr;
  }


}
